export type ReverbShippingRegion = (typeof ReverbShippingRegions)[number];

export const ReverbShippingRegions = [
  { code: 'EUR_EU', name: 'European Union', region_type: 'superregion' },
  { code: 'EUR_NON_EU', name: 'Europe (Non-EU)', region_type: 'superregion' },
  { code: 'ASIA', name: 'Asia', region_type: 'superregion' },
  { code: 'NORTH_AMERICA', name: 'North America', region_type: 'superregion' },
  { code: 'SOUTH_AMERICA', name: 'South America', region_type: 'superregion' },
  { code: 'OCEANIA', name: 'Oceania', region_type: 'superregion' },
  { code: 'AFRICA', name: 'Africa', region_type: 'superregion' },
  { code: 'AD', name: 'Andorra', region_type: 'country' },
  { code: 'AE', name: 'United Arab Emirates', region_type: 'country' },
  { code: 'AF', name: 'Afghanistan', region_type: 'country' },
  { code: 'AG', name: 'Antigua and Barbuda', region_type: 'country' },
  { code: 'AI', name: 'Anguilla', region_type: 'country' },
  { code: 'AL', name: 'Albania', region_type: 'country' },
  { code: 'AM', name: 'Armenia', region_type: 'country' },
  { code: 'AO', name: 'Angola', region_type: 'country' },
  { code: 'AR', name: 'Argentina', region_type: 'country' },
  { code: 'AS', name: 'American Samoa', region_type: 'country' },
  { code: 'AT', name: 'Austria', region_type: 'country' },
  { code: 'AU', name: 'Australia', region_type: 'country' },
  { code: 'AW', name: 'Aruba', region_type: 'country' },
  { code: 'AX', name: 'Åland Islands', region_type: 'country' },
  { code: 'AZ', name: 'Azerbaijan', region_type: 'country' },
  { code: 'BA', name: 'Bosnia and Herzegovina', region_type: 'country' },
  { code: 'BB', name: 'Barbados', region_type: 'country' },
  { code: 'BD', name: 'Bangladesh', region_type: 'country' },
  { code: 'BE', name: 'Belgium', region_type: 'country' },
  { code: 'BF', name: 'Burkina Faso', region_type: 'country' },
  { code: 'BG', name: 'Bulgaria', region_type: 'country' },
  { code: 'BH', name: 'Bahrain', region_type: 'country' },
  { code: 'BI', name: 'Burundi', region_type: 'country' },
  { code: 'BJ', name: 'Benin', region_type: 'country' },
  { code: 'BL', name: 'Saint Barthélemy', region_type: 'country' },
  { code: 'BM', name: 'Bermuda', region_type: 'country' },
  { code: 'BN', name: 'Brunei Darussalam', region_type: 'country' },
  {
    code: 'BO',
    name: 'Bolivia, Plurinational State of',
    region_type: 'country',
  },
  {
    code: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    region_type: 'country',
  },
  { code: 'BR', name: 'Brazil', region_type: 'country' },
  { code: 'BS', name: 'Bahamas', region_type: 'country' },
  { code: 'BT', name: 'Bhutan', region_type: 'country' },
  { code: 'BV', name: 'Bouvet Island', region_type: 'country' },
  { code: 'BW', name: 'Botswana', region_type: 'country' },
  { code: 'BY', name: 'Belarus', region_type: 'country' },
  { code: 'BZ', name: 'Belize', region_type: 'country' },
  { code: 'CA', name: 'Canada', region_type: 'country' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', region_type: 'country' },
  {
    code: 'CD',
    name: 'Congo, The Democratic Republic of the',
    region_type: 'country',
  },
  { code: 'CF', name: 'Central African Republic', region_type: 'country' },
  { code: 'CG', name: 'Congo', region_type: 'country' },
  { code: 'CH', name: 'Switzerland', region_type: 'country' },
  { code: 'CI', name: "Côte d'Ivoire", region_type: 'country' },
  { code: 'CK', name: 'Cook Islands', region_type: 'country' },
  { code: 'CL', name: 'Chile', region_type: 'country' },
  { code: 'CM', name: 'Cameroon', region_type: 'country' },
  { code: 'CN', name: 'China', region_type: 'country' },
  { code: 'CO', name: 'Colombia', region_type: 'country' },
  { code: 'CR', name: 'Costa Rica', region_type: 'country' },
  { code: 'CV', name: 'Cabo Verde', region_type: 'country' },
  { code: 'CW', name: 'Curaçao', region_type: 'country' },
  { code: 'CX', name: 'Christmas Island', region_type: 'country' },
  { code: 'CY', name: 'Cyprus', region_type: 'country' },
  { code: 'CZ', name: 'Czechia', region_type: 'country' },
  { code: 'DE', name: 'Germany', region_type: 'country' },
  { code: 'DJ', name: 'Djibouti', region_type: 'country' },
  { code: 'DK', name: 'Denmark', region_type: 'country' },
  { code: 'DM', name: 'Dominica', region_type: 'country' },
  { code: 'DO', name: 'Dominican Republic', region_type: 'country' },
  { code: 'DZ', name: 'Algeria', region_type: 'country' },
  { code: 'EC', name: 'Ecuador', region_type: 'country' },
  { code: 'EE', name: 'Estonia', region_type: 'country' },
  { code: 'EG', name: 'Egypt', region_type: 'country' },
  { code: 'EH', name: 'Western Sahara', region_type: 'country' },
  { code: 'ER', name: 'Eritrea', region_type: 'country' },
  { code: 'ES', name: 'Spain', region_type: 'country' },
  { code: 'ET', name: 'Ethiopia', region_type: 'country' },
  { code: 'FI', name: 'Finland', region_type: 'country' },
  { code: 'FJ', name: 'Fiji', region_type: 'country' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', region_type: 'country' },
  {
    code: 'FM',
    name: 'Micronesia, Federated States of',
    region_type: 'country',
  },
  { code: 'FO', name: 'Faroe Islands', region_type: 'country' },
  { code: 'FR', name: 'France', region_type: 'country' },
  { code: 'GA', name: 'Gabon', region_type: 'country' },
  { code: 'GB', name: 'United Kingdom', region_type: 'country' },
  { code: 'GD', name: 'Grenada', region_type: 'country' },
  { code: 'GE', name: 'Georgia', region_type: 'country' },
  { code: 'GF', name: 'French Guiana', region_type: 'country' },
  { code: 'GG', name: 'Guernsey', region_type: 'country' },
  { code: 'GH', name: 'Ghana', region_type: 'country' },
  { code: 'GI', name: 'Gibraltar', region_type: 'country' },
  { code: 'GL', name: 'Greenland', region_type: 'country' },
  { code: 'GM', name: 'Gambia', region_type: 'country' },
  { code: 'GN', name: 'Guinea', region_type: 'country' },
  { code: 'GP', name: 'Guadeloupe', region_type: 'country' },
  { code: 'GQ', name: 'Equatorial Guinea', region_type: 'country' },
  { code: 'GR', name: 'Greece', region_type: 'country' },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    region_type: 'country',
  },
  { code: 'GT', name: 'Guatemala', region_type: 'country' },
  { code: 'GU', name: 'Guam', region_type: 'country' },
  { code: 'GW', name: 'Guinea-Bissau', region_type: 'country' },
  { code: 'GY', name: 'Guyana', region_type: 'country' },
  { code: 'HK', name: 'Hong Kong', region_type: 'country' },
  {
    code: 'HM',
    name: 'Heard Island and McDonald Islands',
    region_type: 'country',
  },
  { code: 'HN', name: 'Honduras', region_type: 'country' },
  { code: 'HR', name: 'Croatia', region_type: 'country' },
  { code: 'HT', name: 'Haiti', region_type: 'country' },
  { code: 'HU', name: 'Hungary', region_type: 'country' },
  { code: 'ID', name: 'Indonesia', region_type: 'country' },
  { code: 'IE', name: 'Ireland', region_type: 'country' },
  { code: 'IL', name: 'Israel', region_type: 'country' },
  { code: 'IM', name: 'Isle of Man', region_type: 'country' },
  { code: 'IN', name: 'India', region_type: 'country' },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
    region_type: 'country',
  },
  { code: 'IQ', name: 'Iraq', region_type: 'country' },
  { code: 'IS', name: 'Iceland', region_type: 'country' },
  { code: 'IT', name: 'Italy', region_type: 'country' },
  { code: 'JE', name: 'Jersey', region_type: 'country' },
  { code: 'JM', name: 'Jamaica', region_type: 'country' },
  { code: 'JO', name: 'Jordan', region_type: 'country' },
  { code: 'JP', name: 'Japan', region_type: 'country' },
  { code: 'KE', name: 'Kenya', region_type: 'country' },
  { code: 'KG', name: 'Kyrgyzstan', region_type: 'country' },
  { code: 'KH', name: 'Cambodia', region_type: 'country' },
  { code: 'KI', name: 'Kiribati', region_type: 'country' },
  { code: 'KM', name: 'Comoros', region_type: 'country' },
  { code: 'KN', name: 'Saint Kitts and Nevis', region_type: 'country' },
  { code: 'KR', name: 'Korea, Republic of', region_type: 'country' },
  { code: 'KW', name: 'Kuwait', region_type: 'country' },
  { code: 'KY', name: 'Cayman Islands', region_type: 'country' },
  { code: 'KZ', name: 'Kazakhstan', region_type: 'country' },
  {
    code: 'LA',
    name: "Lao People's Democratic Republic",
    region_type: 'country',
  },
  { code: 'LB', name: 'Lebanon', region_type: 'country' },
  { code: 'LC', name: 'Saint Lucia', region_type: 'country' },
  { code: 'LI', name: 'Liechtenstein', region_type: 'country' },
  { code: 'LK', name: 'Sri Lanka', region_type: 'country' },
  { code: 'LR', name: 'Liberia', region_type: 'country' },
  { code: 'LS', name: 'Lesotho', region_type: 'country' },
  { code: 'LT', name: 'Lithuania', region_type: 'country' },
  { code: 'LU', name: 'Luxembourg', region_type: 'country' },
  { code: 'LV', name: 'Latvia', region_type: 'country' },
  { code: 'LY', name: 'Libya', region_type: 'country' },
  { code: 'MA', name: 'Morocco', region_type: 'country' },
  { code: 'MC', name: 'Monaco', region_type: 'country' },
  { code: 'MD', name: 'Moldova, Republic of', region_type: 'country' },
  { code: 'ME', name: 'Montenegro', region_type: 'country' },
  { code: 'MF', name: 'Saint Martin (French part)', region_type: 'country' },
  { code: 'MG', name: 'Madagascar', region_type: 'country' },
  { code: 'MH', name: 'Marshall Islands', region_type: 'country' },
  { code: 'MK', name: 'North Macedonia', region_type: 'country' },
  { code: 'ML', name: 'Mali', region_type: 'country' },
  { code: 'MM', name: 'Myanmar', region_type: 'country' },
  { code: 'MN', name: 'Mongolia', region_type: 'country' },
  { code: 'MO', name: 'Macao', region_type: 'country' },
  { code: 'MP', name: 'Northern Mariana Islands', region_type: 'country' },
  { code: 'MQ', name: 'Martinique', region_type: 'country' },
  { code: 'MR', name: 'Mauritania', region_type: 'country' },
  { code: 'MS', name: 'Montserrat', region_type: 'country' },
  { code: 'MT', name: 'Malta', region_type: 'country' },
  { code: 'MU', name: 'Mauritius', region_type: 'country' },
  { code: 'MV', name: 'Maldives', region_type: 'country' },
  { code: 'MW', name: 'Malawi', region_type: 'country' },
  { code: 'MX', name: 'Mexico', region_type: 'country' },
  { code: 'MY', name: 'Malaysia', region_type: 'country' },
  { code: 'MZ', name: 'Mozambique', region_type: 'country' },
  { code: 'NA', name: 'Namibia', region_type: 'country' },
  { code: 'NC', name: 'New Caledonia', region_type: 'country' },
  { code: 'NE', name: 'Niger', region_type: 'country' },
  { code: 'NF', name: 'Norfolk Island', region_type: 'country' },
  { code: 'NG', name: 'Nigeria', region_type: 'country' },
  { code: 'NI', name: 'Nicaragua', region_type: 'country' },
  { code: 'NL', name: 'Netherlands', region_type: 'country' },
  { code: 'NO', name: 'Norway', region_type: 'country' },
  { code: 'NP', name: 'Nepal', region_type: 'country' },
  { code: 'NR', name: 'Nauru', region_type: 'country' },
  { code: 'NU', name: 'Niue', region_type: 'country' },
  { code: 'NZ', name: 'New Zealand', region_type: 'country' },
  { code: 'OM', name: 'Oman', region_type: 'country' },
  { code: 'PA', name: 'Panama', region_type: 'country' },
  { code: 'PE', name: 'Peru', region_type: 'country' },
  { code: 'PF', name: 'French Polynesia', region_type: 'country' },
  { code: 'PG', name: 'Papua New Guinea', region_type: 'country' },
  { code: 'PH', name: 'Philippines', region_type: 'country' },
  { code: 'PK', name: 'Pakistan', region_type: 'country' },
  { code: 'PL', name: 'Poland', region_type: 'country' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', region_type: 'country' },
  { code: 'PN', name: 'Pitcairn', region_type: 'country' },
  { code: 'PS', name: 'Palestine, State of', region_type: 'country' },
  { code: 'PT', name: 'Portugal', region_type: 'country' },
  { code: 'PW', name: 'Palau', region_type: 'country' },
  { code: 'PY', name: 'Paraguay', region_type: 'country' },
  { code: 'QA', name: 'Qatar', region_type: 'country' },
  { code: 'RE', name: 'Réunion', region_type: 'country' },
  { code: 'RO', name: 'Romania', region_type: 'country' },
  { code: 'RS', name: 'Serbia', region_type: 'country' },
  { code: 'RU', name: 'Russia', region_type: 'country' },
  { code: 'RW', name: 'Rwanda', region_type: 'country' },
  { code: 'SA', name: 'Saudi Arabia', region_type: 'country' },
  { code: 'SB', name: 'Solomon Islands', region_type: 'country' },
  { code: 'SC', name: 'Seychelles', region_type: 'country' },
  { code: 'SE', name: 'Sweden', region_type: 'country' },
  { code: 'SG', name: 'Singapore', region_type: 'country' },
  {
    code: 'SH',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    region_type: 'country',
  },
  { code: 'SI', name: 'Slovenia', region_type: 'country' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', region_type: 'country' },
  { code: 'SK', name: 'Slovakia', region_type: 'country' },
  { code: 'SL', name: 'Sierra Leone', region_type: 'country' },
  { code: 'SM', name: 'San Marino', region_type: 'country' },
  { code: 'SN', name: 'Senegal', region_type: 'country' },
  { code: 'SO', name: 'Somalia', region_type: 'country' },
  { code: 'SR', name: 'Suriname', region_type: 'country' },
  { code: 'SS', name: 'South Sudan', region_type: 'country' },
  { code: 'ST', name: 'Sao Tome and Principe', region_type: 'country' },
  { code: 'SV', name: 'El Salvador', region_type: 'country' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', region_type: 'country' },
  { code: 'SZ', name: 'Eswatini', region_type: 'country' },
  { code: 'TC', name: 'Turks and Caicos Islands', region_type: 'country' },
  { code: 'TD', name: 'Chad', region_type: 'country' },
  { code: 'TG', name: 'Togo', region_type: 'country' },
  { code: 'TH', name: 'Thailand', region_type: 'country' },
  { code: 'TJ', name: 'Tajikistan', region_type: 'country' },
  { code: 'TK', name: 'Tokelau', region_type: 'country' },
  { code: 'TL', name: 'Timor-Leste', region_type: 'country' },
  { code: 'TM', name: 'Turkmenistan', region_type: 'country' },
  { code: 'TN', name: 'Tunisia', region_type: 'country' },
  { code: 'TO', name: 'Tonga', region_type: 'country' },
  { code: 'TR', name: 'Turkey', region_type: 'country' },
  { code: 'TT', name: 'Trinidad and Tobago', region_type: 'country' },
  { code: 'TV', name: 'Tuvalu', region_type: 'country' },
  { code: 'TW', name: 'Taiwan', region_type: 'country' },
  { code: 'TZ', name: 'Tanzania, United Republic of', region_type: 'country' },
  { code: 'UA', name: 'Ukraine', region_type: 'country' },
  { code: 'UG', name: 'Uganda', region_type: 'country' },
  {
    code: 'UM',
    name: 'United States Minor Outlying Islands',
    region_type: 'country',
  },
  { code: 'US', name: 'United States', region_type: 'country' },
  { code: 'UY', name: 'Uruguay', region_type: 'country' },
  { code: 'UZ', name: 'Uzbekistan', region_type: 'country' },
  { code: 'VA', name: 'Holy See (Vatican City State)', region_type: 'country' },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    region_type: 'country',
  },
  {
    code: 'VE',
    name: 'Venezuela, Bolivarian Republic of',
    region_type: 'country',
  },
  { code: 'VG', name: 'Virgin Islands, British', region_type: 'country' },
  { code: 'VI', name: 'Virgin Islands, U.S.', region_type: 'country' },
  { code: 'VN', name: 'Vietnam', region_type: 'country' },
  { code: 'VU', name: 'Vanuatu', region_type: 'country' },
  { code: 'WF', name: 'Wallis and Futuna', region_type: 'country' },
  { code: 'WS', name: 'Samoa', region_type: 'country' },
  { code: 'YE', name: 'Yemen', region_type: 'country' },
  { code: 'YT', name: 'Mayotte', region_type: 'country' },
  { code: 'ZA', name: 'South Africa', region_type: 'country' },
  { code: 'ZM', name: 'Zambia', region_type: 'country' },
  { code: 'ZW', name: 'Zimbabwe', region_type: 'country' },
  { code: 'US_AK', name: 'Alaska', region_type: 'subregion' },
  { code: 'US_HI', name: 'Hawaii', region_type: 'subregion' },
  { code: 'US_PR', name: 'Puerto Rico', region_type: 'subregion' },
  {
    code: 'US_OTHER',
    name: 'Other U.S. Territories',
    region_type: 'subregion',
  },
  { code: 'US_CON', name: 'Continental U.S.', region_type: 'subregion' },
  { code: 'XX', name: 'Everywhere Else', region_type: 'everywhere_else' },
] as const;
